# Generated by Django 3.0.8 on 2021-03-03 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='mobile',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
